import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "@/components/menu";
import { ServiceWorkerRegistrar } from "@/components/ServiceWorkerRegistrar";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="кг"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="flex flex-col items-center min-h-full bg-[#f5f5f5]">
        <Analytics />
        <SpeedInsights />
        <ServiceWorkerRegistrar />
        <main className="w-full p-4 mb-24">{children}</main>
        <Menu />
      </body>
    </html>
  );
}
